services:
  - type: web
    name: stock-analysis-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run main.py
    staticPublishPath: /static
    autoDeploy: true
